//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exxis.Addon.HojadeRutaAGuia.CrossCutting.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Exxis.Addon.HojadeRutaAGuia.CrossCutting.Resources.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [Internal Error] The column match for the &apos;MatrixBuilder&apos; has errors.
        /// </summary>
        public static string BadMatchMatrixBuilder {
            get {
                return ResourceManager.GetString("BadMatchMatrixBuilder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [Internal Error] Can&apos;t load the class &apos;ApplicationSettings&apos; because {0}.
        /// </summary>
        public static string LoadApplicationSettings {
            get {
                return ResourceManager.GetString("LoadApplicationSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [Internal Error] The expression &apos;{0}&apos; doesn&apos;t have implemented in this version.
        /// </summary>
        public static string MissmatchExpression {
            get {
                return ResourceManager.GetString("MissmatchExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [Internal Error] The value &apos;{0}&apos; doesn&apos;t have implemented in this version.
        /// </summary>
        public static string MissmatchSAPDatabaseType {
            get {
                return ResourceManager.GetString("MissmatchSAPDatabaseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [Internal Error] The class &apos;{0}&apos; is not reference/base type for &apos;{1}&apos;.
        /// </summary>
        public static string MissmatchType {
            get {
                return ResourceManager.GetString("MissmatchType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [Internal Error] The instance of &apos;{0}&apos; doesn&apos;t have implemented in this version.
        /// </summary>
        public static string NoImplemented {
            get {
                return ResourceManager.GetString("NoImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [Internal Error] Error con el API externo ({0}) - {1}.
        /// </summary>
        public static string NotConnectWithAPI {
            get {
                return ResourceManager.GetString("NotConnectWithAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [Internal Error] The class &apos;{0}&apos; don&apos;t have required attribute &apos;{1}&apos;.
        /// </summary>
        public static string RequiredAttributeDontFound {
            get {
                return ResourceManager.GetString("RequiredAttributeDontFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La linea &apos;{0}&apos; del documento no posee suficientes articulos a distribuir.
        /// </summary>
        public static string SaleOrderValidationError {
            get {
                return ResourceManager.GetString("SaleOrderValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La linea &apos;{0}&apos; del documento tiene un TVU superior a lo disponible.
        /// </summary>
        public static string SaleOrderValidationErrorTVU {
            get {
                return ResourceManager.GetString("SaleOrderValidationErrorTVU", resourceCulture);
            }
        }
    }
}
